version: "3.8"
services:
       redis:
         image: "redis:latest"
         ports:
           - "6379:6379"
       web:
         build:
           context: .
           dockerfile: Dockerfile
         ports:
           - "3000:3000"
         depends_on:
           - redis