version: "3.8"
services:
       redis:
         container_name: redis-server
         image: redis:latest
         hostname: redis
         ports:
           - 6379:6379
         healthcheck:
           test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
           interval: 1s
           timeout: 3s
           retries: 5
       web:
         build:
           context: .
           dockerfile: Dockerfile
         ports:
           - "3000:3000"
         depends_on:
           - redis